deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ABE5C56D4C0F4DC692CAA22BF1C46EF3 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E794F52F22914538BE993024EF2F10F5 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C503EBB06F80442B9A82B309A1125BEA }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fiap-simple-api-dev2'
        slot-name: 'Production'
        images: 'index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7FCE8F82737D4004A7B6EC208F2B88F5 }}/luizfelipe21/simple-api-java:${{ github.sha }}'